version: '3.8'

services:
  tgfilebot:
    image: ghcr.io/lm317379829/tgfilebot:latest
    container_name: tgfilebot
    restart: unless-stopped
    ports:
      - "9981:8080"
    volumes:
      - ./files:/root/files
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
